package com.example.popcorntime.modules.movie_details.domain.models

data class MovieDetailsDomainModel(
    val id: Long?,
    val adult: Boolean?,
    val backdropPath: String?,
    val genreIDS: List<Long>?,
    val originalLanguage: String?,
    val originalTitle: String?,
    val overview: String?,
    val popularity: Double?,
    val posterPath: String?,
    val releaseDate: String?,
    val title: String?,
    val video: Boolean?,
    val voteAverage: Double?,
    val voteCount: Long?,
    val belongsToCollection: BelongsToCollectionDomainModel?,
    val budget: Long?,
    val genres: List<GenreDomainModel>?,
    val homepage: String?,
    val imdbID: String?,
    val productionCompanies: List<ProductionCompanyDomainModel>?,
    val productionCountries: List<ProductionCountryDomainModel>?,
    val revenue: Long?,
    val runtime: Long?,
    val spokenLanguages: List<SpokenLanguageDomainModel>?,
    val status: String?,
    val tagline: String?,
)